# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'MydevOpsCon'
    command: 'build'
    projects: '''**/*.csproj'''
    arguments: '-r win-x64 -p:PublishSingleFile=True --self-contained false -o $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
  enabled: true 
     
  
     